# Composing tweets

The most common question I get at social media workshops that I've run is, "What should I tweet?". There is no easy answer to this, because every researcher and their subfield is different. But regardless of your subfield, _the best way to engage your followers is to either entertain or educate_. In other words, you should aim to help people either pass time or save time. Being entertaining doesn't come naturally to most people, so don't worry if this isn't you. But as a scientist, you are very well-placed to educate, no matter your level of training.

Thanks to [Chapter 1](#beginner), you're up to speed with the general mechanics of Twitter. You also just learnt about the "entertain or educate" principle, with *any* scientist ready to educate. But even when arriving at this point, many scientists hit a wall, because they believe they can only tweet the finished product of their work, which is typically papers. But as soon as you realise that the *process* of your work is just as interesting as the *output*, then things become much easier. You're going to see a few examples of this below.

When it comes to tweet frequency, it's hard to give any firm recommendations. Whether you're tweeting too much depends on how many people your followers are following, and how much *they* tweet. So, this means that the "too much" threshold is different for everyone. In my opinion, I think it's fairly difficult to tweet too much. In the early days of Twitter (or any social network), where users didn't follow that many people, it was pretty easy to flood someone's timeline. But now, people tend to follow hundreds (sometimes thousands) of accounts, so this is harder to do. I think the upside of more tweets outweighs the downside a few people unfollowing you because they think you tweet too much. You never know which tweets other people will find interesting.

Well-written tweets reduce friction and uncertainty. For example, people are more likely to click on a link to a paper if they can read the abstract first, in an attached image. By including an image of an abstract, people can quickly scan if the paper is worth accessing.

## Some example tweets

### Tweeting about your own research papers

This is one of the most common tweets you'll see from scientists who aren't very active on Twitter. When a new paper is published, they'll log on, post the title of their paper with a link to the paper, and then log off until their next paper is published. There are so many more types of tweets that you can compose, but I'm going to walk through how you can lift your game with these types of tweets, which are one of the main reasons many scientists are on Twitter.

__1. Add an image from the paper to go with the tweet.__ Have a look through the paper to see if there's a nice image that can be used. If there are no images, you can just take a screenshot of the abstract or a particularly interesting part of the paper. [Skitch](https://evernote.com/products/skitch) is a handy app for screenshots, as you can easily annotate and highlight images. 

__2. Add a quote from the paper.__ Find a striking quote from the paper to include in your tweet. You can either write this as text, or take a screenshot of it and then highlight the quote.

__3. Tag your co-authors and the journal.__ Co-authored papers are a team effort, so you should acknowledge your team. In addition, this gives your followers the chance to find more people to follow.

__4. Add your own commentary of the paper.__ If you're not including a quote, you should share *why* you think the paper is interesting. 

__5. Add a link to a non-paywalled version of the paper.__ People might see the tweet, but not bother clicking on the link if they do not have institutional access to the journal. However, if you include a link to a preprint or a postprint^[A preprint is a version of an article that is posted to a preprint repository before peer-review. Most journals allow you to submit papers that have been posted as preprints and do not consider this dual-publication. Check your journal's policies. A postprint is a version of paper that has undergone peer-review but has not been typeset. These are typically posted to the author's personal or institutional website. Postprints are usually just a PDF version of the final Word document that was sent to the journal. Unlike preprints, journal policies vary regarding postprints, so it's best to check before uploading one.], then people know they can easily access the paper.

In the following example of a paper I co-authored, I mention a summary of the results, tag my co-authors who are on Twitter, include a link to a postprint of the article, and attach a figure from the article.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">New paper! Intranasal oxytocin abolishes the self-referential bias in terms of reaction time (n = 170), replicating prior results <a href="https://t.co/3m9TxBIYis">https://t.co/3m9TxBIYis</a> Great work from Weihua Zhao, <a href="https://twitter.com/bn_becker?ref_src=twsrc%5Etfw">@bn_becker</a> + Chengdu team and <a href="https://twitter.com/ChrisMontag77?ref_src=twsrc%5Etfw">@ChrisMontag77</a>. Non-paywalled version: <a href="https://t.co/lzQ1wknUQ1">https://t.co/lzQ1wknUQ1</a> <a href="https://t.co/sKd1p3FAyU">pic.twitter.com/sKd1p3FAyU</a></p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1161171300037079040?ref_src=twsrc%5Etfw">August 13, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Here's another good example, with [\@GuyProchilo](https://twitter.com/GuyProchilo) sharing his first first-author paper. Notice that Guy tags his co-authors, the journal, adds a hashtag (#IOpsych) relevant to his research field in this tweet (Industrial-organisational psychology), and includes a nice image of the paper.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I’m excited to announce my first first-author paper - published in <a href="https://twitter.com/Meta_Psy?ref_src=twsrc%5Etfw">@Meta_Psy</a>!<br><br>“An Extended Commentary on Post-Publication Peer Review In Organizational Neuroscience”: <a href="https://t.co/VmbZvgcxE8">https://t.co/VmbZvgcxE8</a><br><br>Coauthored by <a href="https://twitter.com/WLouisUQ?ref_src=twsrc%5Etfw">@WLouisUQ</a>, <a href="https://twitter.com/DLabMelbourne?ref_src=twsrc%5Etfw">@DLabMelbourne</a>, <a href="https://twitter.com/HannesZacher?ref_src=twsrc%5Etfw">@HannesZacher</a>, &amp; <a href="https://twitter.com/Social_Neuro_M?ref_src=twsrc%5Etfw">@Social_Neuro_M</a><a href="https://twitter.com/hashtag/IOpsych?src=hash&amp;ref_src=twsrc%5Etfw">#IOpsych</a> <a href="https://t.co/g8tiY9xp6V">pic.twitter.com/g8tiY9xp6V</a></p>&mdash; Guy Prochilo 🏳️
🌈 (@GuyProchilo) <a href="https://twitter.com/GuyProchilo/status/1197095447757606919?ref_src=twsrc%5Etfw">November 20, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

While single tweets announcing new papers can be an effective way to share your new work, I think a thread does a better job---see [Chapter 4](#advanced-twitter-skills) for how to make an effective thread to introduce your new work.

### Tweeting about other people's research papers

There are only so many articles that you can co-author. So in addition, you should also share papers that you find interesting.

Below is an example of tweeting a link to a new paper, in which I added an image and quote from the paper, and mentioned the lead author and the journal that it was published in.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Effects of route of administration on oxytocin-induced changes in rCBF in humans <a href="https://t.co/Ibfv97VZ3T">https://t.co/Ibfv97VZ3T</a> <br><br>“....we also provide robust evidence confirming the validity of the intranasal route to target specific brain regions” Great work from <a href="https://twitter.com/DanielArturAM?ref_src=twsrc%5Etfw">@DanielArturAM</a> + team in <a href="https://twitter.com/NatureComms?ref_src=twsrc%5Etfw">@NatureComms</a> <a href="https://t.co/J8H97nkgBT">pic.twitter.com/J8H97nkgBT</a></p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1234808705666908162?ref_src=twsrc%5Etfw">March 3, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Sharing information about yourself

Twitter provides a great way to connect with other researchers and to share information about yourself that you typically can't convey in a scientific paper. Here's an example from [\@_DaniBeck](https://twitter.com/_DaniBeck). 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">What did you work on for your undergrad vs postgrad?<br><br>BSc:<br>&quot;the effects of ethnocentrism on automatic stereotyping&quot;<br><br>MSc:<br>&quot;a needs analysis of the population at HMP Birmingham: A service evaluation&quot;<br><br>Mphil:<br>&quot;The Neurotrophic Effect of Antidepressant Drugs on Hippocampal Volume⁰&quot;</p>&mdash; ᴅᴀɴɪ ʙᴇᴄᴋ ❼ (@_DaniBeck) <a href="https://twitter.com/_DaniBeck/status/1230448824277196800?ref_src=twsrc%5Etfw">February 20, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Sharing your toolkit

As scientists, we use several tools in our day-to-day work. Even if these tools seem commonplace to you, your followers will appreciate learning about new ways to do their work. Here's an example of me tweeting about the ['bookdown' R package](https://bookdown.org/home/), which I've used to write this book. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Starting to get the hang of the {bookdown} <a href="https://twitter.com/hashtag/Rstats?src=hash&amp;ref_src=twsrc%5Etfw">#Rstats</a> package, super impressed! Check out this package if you&#39;ve ever wanted to put together a book, technical document, or long-form document <a href="https://t.co/5Wa4ISkYUG">https://t.co/5Wa4ISkYUG</a></p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1235114385569439744?ref_src=twsrc%5Etfw">March 4, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Notice that the link has been converted into a small image with information, which is called a [Twitter Card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards). This is a feature of more modern websites, which include Twitter Card information in their underlying code. If you're Tweeting from your phone, the Twitter Card will appear, if it's available, as soon as you enter the link. This doesn't occur when tweeting from your desktop, but you can quickly check if there's a Twitter card associated with the link you're going to post on the [Twitter Card Validator](https://cards-dev.twitter.com/validator) website. 

### Asking a question

Twitter can be a really great way to get advice. If you don't have many followers, you should also consider tagging experts that might know the answer (but don't spam people, so use this sparingly). Here's an example that I used, which was also used for researching this book.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I’m putting something together on twitter profile/bio pages for an upcoming talk. <br><br>What do you think makes a ‘good’ twitter profile, when it comes to images, text, web URL etc...? What makes you think, “Yeah, I’m going to follow them...”?</p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1234836938106003456?ref_src=twsrc%5Etfw">March 3, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Sharing memes

Memes are fun, but also a good way to demonstrate knowledge and authority in your area. Notice in this example that this tweet was a quote retweet, so that people can see that I've remixed someone else's tweet.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Hi, I’m a psychoneuroendocrinologist. You might know me from my smash hits: “Don’t Buy Oxytocin Online”, “You Can’t Measure Peripheral Blood Oxytocin Levels to Infer Brain Levels”, and “Your Sample Size is Too Small”, OR my chart-topping “Oxytocin Is Not the Cuddle Chemical” <a href="https://t.co/gWdNe1quX0">https://t.co/gWdNe1quX0</a></p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1234446547456266240?ref_src=twsrc%5Etfw">March 2, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Sharing videos 

You can include a video that's up to two minutes and twenty seconds long to your tweets. In the following tweet, I've included a link to an eleven-minute instructional YouTube video. I can't show the entire video due to Twitter's limits, so I've included a short preview to entice people to click on the link to the full video.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">How to make a reproducible version of your <a href="https://twitter.com/hashtag/Rstats?src=hash&amp;ref_src=twsrc%5Etfw">#Rstats</a> analysis that can be run in any modern web browser, using <a href="https://twitter.com/_inundata?ref_src=twsrc%5Etfw">@_inundata</a>’s &#39;holepunch&#39; package + <a href="https://twitter.com/mybinderteam?ref_src=twsrc%5Etfw">@mybinderteam</a> <br><br>Full screencast w/links [11 mins] 👉 <a href="https://t.co/5sjlN0iY4h">https://t.co/5sjlN0iY4h</a><br><br>Preview 👇 <a href="https://t.co/SsX8qozMJ8">pic.twitter.com/SsX8qozMJ8</a></p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1162002047794864128?ref_src=twsrc%5Etfw">August 15, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


### Documenting your experiences

I hardly ever sit down and think, "what will I tweet?". Most of my tweets are simply offcuts of work I'm already doing, or things I'm already discussing in real life.

For example, I was recenlty having a chat with some colleagues about grant applications. I told them a principle I used to write my applications, which they found useful. So I turned this into a tweet, which also seemed to resonate on Twitter.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Every grant application introduction I write indirectly answers these four ‘why’ questions:<br><br>1. Why this?<br>2. Why me?<br>3. Why here?<br>4. Why now?</p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1233838022224941061?ref_src=twsrc%5Etfw">February 29, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Here's another example of ["showing my work"](https://austinkleon.com/show-your-work/). I didn't have to think of something new to tweet, as I essentially copy and pasted my reply email.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Got an email from a new grad student asking for recommendations for resources to better understand research design and statistical inference. Here’s what I’m going to tell them...</p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1150349430303989761?ref_src=twsrc%5Etfw">July 14, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Peer review is a task that most of us do, so you can take this opportunity to make a wider point about your research topic. For instance, I recently shared a point about power analysis using a peer-review I was conducting.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Reviewing a paper with no power analysis, so I did one for them! <br><br>The main outcome was tested using a paired-samples t-test, with 25 participants in total. So I plugged these numbers into the <a href="https://twitter.com/jamovistats?ref_src=twsrc%5Etfw">@jamovistats</a> &#39;jpower&#39; module and got these results ⤵️ <br><br>1/2 <a href="https://t.co/ImOmhhTMDI">pic.twitter.com/ImOmhhTMDI</a></p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1235109801543086082?ref_src=twsrc%5Etfw">March 4, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Let's break down this tweet:

1. I used a line break to clearly separate the two parts of this tweet.
2. The screenshot image is eye catching (especially the plot) and conveys a lot of information.
3. The 'down arrow' emoji adds a tiny bit of flair.
4. I tagged a tool that I mentioned [\@Jamovistats](https://twitter.com/Jamovistats), so that followers could easily find out more.
5. I numbered this tweet "1/2", to signal that this is a two-part tweet. My followers will see these two tweets back-to-back, but people who see this tweet as a retweet will now know there is more than one tweet on this topic, and can then check the full conversation.

Of course, if you're going to tweet about peer review you will need to keep things as anonymous as possible! 

You can also tweet about being at the *other end* of the peer review process.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Reviewer 1: Expand the third paragraph of your discussion as it’s critical for your paper <br><br>Reviewer 2: Delete the third paragraph of your discussion as it weakens your paper <a href="https://t.co/t6OPE5MWUx">pic.twitter.com/t6OPE5MWUx</a></p>&mdash; Dan Quintana (@dsquintana) <a href="https://twitter.com/dsquintana/status/1184586845935546370?ref_src=twsrc%5Etfw">October 16, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Remember, the key is sharing the process of your work, not just the final product.